import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import Image from "next/image";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <header className="bg-gray-800 py-6 h-[74px]">
          <div className="container">
            <Image src="/tmdb-logo.svg" alt="logo" width={60} height={24} />
            <nav></nav>
          </div>
        </header>
        <div
          className="bg-gradient-to-b from-slate-400 to-slate-300"
          style={{ height: "calc(100vh - 74px)", overflow: "scroll" }}
        >
          {children}
        </div>
      </body>
    </html>
  );
}
